#!/bin/bash
#$1 = folder name
#$2 = starting letter

if [[ "$#" != 2 ]];then
  # checks if 2 arguments were inserted	
	echo 'Not enough parameters'
	exit 1
fi

if [ ! -d "$1" ]; then 
  # checks if the directory exists
	echo 'Directory does not exist' 
  exit 1
fi
dir_name="$1"
first_letter="$2"
echo `find ./"$dir_name"/ -type f -name "[${first_letter,,}${first_letter^^}]*" | wc -l` #one liner, yeah!
exit 0